# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nn_model',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nn_model',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
