# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20171113_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='nn_model',
            name='training_counts',
            field=models.IntegerField(default=0),
        ),
    ]
