# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_nn_model_training_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nn_model',
            name='status',
            field=models.CharField(default='idle', max_length=30),
        ),
        migrations.AlterField(
            model_name='nn_model',
            name='state_file',
            field=models.FilePathField(match='state.json', path='/media/disk1/petpen_develop/'),
        ),
        migrations.AlterField(
            model_name='nn_model',
            name='structure_file',
            field=models.FilePathField(match='result.json', path='/media/disk1/petpen_develop/'),
        ),
    ]
