# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20171116_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.DateTimeField(default=django.utils.timezone.now)),
                ('save_path', models.CharField(max_length=20)),
                ('execution_type', models.CharField(max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.NN_model')),
            ],
        ),
    ]
