# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(default='success', max_length=30),
        ),
        migrations.AlterField(
            model_name='history',
            name='execution_type',
            field=models.CharField(default='training model', max_length=15),
        ),
    ]
