# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20180104_0231'),
        ('model', '0007_auto_20171129_2030'),
    ]

    operations = [
    ]
