# Generated by Django 2.0.3 on 2018-03-26 19:21

from django.db import migrations, models
import django.db.models.deletion
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_merge_20180207_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired', models.DateTimeField(default=model.models.one_week_period)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.History')),
            ],
        ),
        migrations.AlterField(
            model_name='nn_model',
            name='state_file',
            field=models.FilePathField(match='state.json', path='/data1/petpen/develop'),
        ),
        migrations.AlterField(
            model_name='nn_model',
            name='structure_file',
            field=models.FilePathField(match='result.json', path='/data1/petpen/develop'),
        ),
    ]
