# Generated by Django 2.0.3 on 2018-04-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_prediction_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='history',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
