# Generated by Django 2.0.3 on 2018-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20180413_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='nn_model',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
