# Generated by Django 2.0.3 on 2018-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_nn_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nn_model',
            name='status',
            field=models.CharField(choices=[('idle', 'system idle'), ('running', 'training model'), ('editing', 'editing model structure'), ('executing', 'predicting dataset'), ('finish', 'finish training'), ('error', 'error found')], default='idle', max_length=30),
        ),
    ]
