FROM ubuntu:17.04
RUN apt-get update && apt-get install -y nodejs npm
RUN npm install -g node-red
RUN ln -s /usr/bin/nodejs /usr/bin/node

RUN mkdir /nodered

ADD nodered/ /nodered
ADD install-nodered.sh /
RUN /install-nodered.sh

# Workaround
RUN rm /usr/local/lib/node_modules/Dense_node

CMD ["node-red"]
