version: '3'

services:
    redis:
        image: redis
    web:
        environment:
            - storage
        image: petpensite_dev
        command: python website/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/source
            - "${storage}:/source/storage"
        ports:
            - "1980:8000"
        depends_on:
            - redis
