FROM tensorflow/tensorflow:latest-gpu

RUN pip install keras django bokeh docker
RUN pip install djangorestframework
RUN pip install django-background-tasks
RUN pip install django-bower django-nvd3

RUN mkdir -p /source
ADD . /source/

WORKDIR /source/website
ENTRYPOINT ["python", "manage.py", "runserver"]
