FROM ubuntu:16.04
RUN apt-get update && apt-get install -y nodejs npm
RUN npm install -g node-red
RUN ln -s /usr/bin/nodejs /usr/bin/node

RUN mkdir /nodered

ADD nodered/ /nodered
ADD install-nodered.sh /
RUN /install-nodered.sh

WORKDIR /app

CMD ["node-red", "-p", "1880", "-u", "."]
